cameras:
  - id: "hp_webcam"
    name: "HP True Vision FHD Camera"
    url: "rtsp://localhost:8554/webcam"
    username: ""
    password: ""
    enabled: true
    detection_enabled: true
    fps_limit: 10
    reconnect_interval: 30
    timeout: 10

last_updated: 2025-06-29T19:25:00Z